version: 2
updates:
  - package-ecosystem: maven
    directory: /quarkus-impl
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /quarkus-impl/src/main/docker
    schedule:
      interval: weekly
